name: Vivado Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-bitstream:
    runs-on: [self-hosted, linux, x64] # Customize this line based on your runner's tags
    strategy:
      matrix:
        boards: [RFSoC4x2, ZCU208]
      fail-fast: false
    steps:
    - uses: actions/checkout@main
      name: Checkout code

    - name: Run Vivado Build
      run: |
        source /tools/Xilinx/Vivado/2020.2/settings64.sh
        cd boards/${{ matrix.boards }}/rfsoc_ofdm/
        make all
        cd ../../..

    # Compress the project directory
    - name: Compress Project
      run: |
        touch rfsoc_ofdm.tar.gz
        tar -czvf rfsoc_ofdm.tar.gz .

    - uses: actions/upload-artifact@v2
      with:
        name: bitstream-archive
        path: rfsoc_ofdm.tar.gz
