name: Vivado Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-RFSoC2x2:
    runs-on: [self-hosted, linux, x64] # Customize this line based on your runner's tags

    steps:
    - uses: actions/checkout@main
      name: Checkout code

    - name: Run Vivado Build
      run: |
        source /tools/Xilinx/Vivado/2020.2/settings64.sh
        cd boards/RFSoC2x2/rfsoc_ofdm/
        make all
